# Generated by Django 4.0.5 on 2022-06-16 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app10', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubBookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('duration', models.CharField(max_length=30)),
                ('feestructure', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('payment_status', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
