# Generated by Django 4.0.5 on 2022-06-22 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app10', '0002_subbookmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='addsubscriptionmodel',
            name='category',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='subbookmodel',
            name='category',
            field=models.CharField(default='', max_length=30),
        ),
    ]
